# --- Dataset Configuration ---
data_dir: '/kaggle/input/bbbc041/dataset_resplit' # Base dir for relative paths if needed

# --- Datasets Configuration (List) ---
datasets:
  - type: 'annotation' # Nguồn dữ liệu này chỉ dùng cho training
    # Settings for 'annotation' type
    annotation_train: '/kaggle/input/datn-smote/smote_custom_strategy_output_structured/smote_annotations.txt'
    annotation_val: null  # Không dùng validation từ nguồn này
    annotation_test: null # Không dùng test từ nguồn này
    annotation_root: '/kaggle/input/datn-smote/smote_custom_strategy_output_structured' # Root cho ảnh của dataset này

  - type: 'imagefolder' # Nguồn dữ liệu này chỉ dùng cho validation và test
    imagefolder_root: '/kaggle/input/bbbc041/dataset_resplit'
    imagefolder_train_subdir: null # Không dùng training từ nguồn này
    imagefolder_val_subdir: 'val'  # Thư mục con cho validation
    imagefolder_test_subdir: 'test' # Thư mục con cho test

batch_size: 64
num_workers: 4 # Adjusted based on typical Kaggle limits

# # --- Class Configuration ---
# class_names:
#   - "Ring"
#   - "Trophozoite"
#   - "Schizont"
#   - "Gametocyte" # Corrected spelling
#   - "Healthy RBC"
#   - "Other"
# --- Class Configuration ---
class_names:
  - "difficult"
  - "gametocyte"
  - "leukocyte"
  - "red blood cell"
  - "ring"
  - "schizont"
  - "trophozoite"
# --- Model Configuration ---
model_names:
  # - mobilenetv4_hybrid_large.e600_r384_in1k # Example timm model
  # - resnet50 # Example torchvision model
  - mobilenetv4_conv_small.e2400_r224_in1k

# --- Training Configuration ---
training:
  num_epochs: 100 # Reduced for example
  patience: 20   # Early stopping patience
  use_amp: false # Use Automatic Mixed Precision (requires CUDA)
  clip_grad_norm: 0 # Max norm for gradient clipping (set to 0 or null to disable)
  train_ratio: 1 # Ratio of the (combined) training set to use (1.0 = 100%, 0.1 = 10%)

# --- Optimizer Configuration ---
optimizer:
  type: AdamW # Options: Adam, AdamW, SGD, etc.
  lr: 1e-4    # Learning Rate moved here
  params: # Parameters specific to the optimizer type
    weight_decay: 0.01 # Example for AdamW

# --- LR Scheduler Configuration ---
scheduler:
  type: CosineAnnealingLR # Options: StepLR, ReduceLROnPlateau, CosineAnnealingLR, etc.
  T_max: 100 # For CosineAnnealingLR: Maximum number of iterations (set to num_epochs)
  eta_min: 1e-6 # For CosineAnnealingLR: Minimum learning rate

# --- Loss Function (Criterion) Configuration ---
criterion: CrossEntropyLoss # Options: CrossEntropyLoss, FocalLoss, F1Loss
criterion_params: # Parameters specific to the criterion
  # For FocalLoss:
  # gamma: 2.0
  # reduction: 'mean'
  # For F1Loss:
  # beta: 1.0
  # epsilon: 1e-7
  # For CrossEntropyLoss:
  use_class_weights: false # Set to true to compute and use class weights

# --- Results Directory ---
results_dir: 'results_kaggle' # Separate results dir for Kaggle runs

# --- Device Configuration ---
device:
  use_cuda: true      # Attempt to use CUDA (GPU) if available
  multi_gpu: true     # Attempt to use DataParallel if multiple GPUs detected
