# Dataset configuration
data_dir: '/kaggle/input/datn-cell/Our_Plasmodium_Classification_Khanh_Thesis_Jan2025/'
root_dataset_dir: '/kaggle/input/datn-cell/Our_Plasmodium_Classification_Khanh_Thesis_Jan2025/cropped_RBCs'
batch_size: 32
num_workers: 4

# Class configuration
class_names:
  - "Ring"
  - "Trophozoite"
  - "Schizont" 
  - "Gemtocyte"
  - "Healthy RBC"
  - "Other"

# Model training configuration
model_names:
  - ese_vovnet57b
num_epochs: 100
patience: 20
learning_rate: 1e-3
step_size: 5
gamma: 0.5
use_amp: false
clip_grad_norm: 1.0  # Add gradient clipping parameter

# Results directory
results_dir: 'results'

# Device configuration
tpu_available: false
use_cuda: true      # Whether to use CUDA (GPU) for computation
multi_gpu: true     # Whether to use DataParallel for multi-GPU training
